name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *" # Atualiza a cada 12 horas
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Geração da cobrinha
        uses: Platane/snk@v3
        with:
          github_user_name: renilson-medeiros
          outputs: dist/github-contribution-grid-snake.svg

      - name: Commit e push
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "Gerando Snake Animation"
          add: "dist"
